# CIRISBridge Terraform Outputs
# Active/Active Multi-Region Configuration

# =============================================================================
# IP Addresses
# =============================================================================

output "us_ip" {
  description = "US node (Vultr) public IPv4"
  value       = vultr_instance.us.main_ip
}

output "us_ipv6" {
  description = "US node (Vultr) public IPv6"
  value       = vultr_instance.us.v6_main_ip
}

output "eu_ip" {
  description = "EU node (Hetzner) public IPv4"
  value       = hcloud_server.eu.ipv4_address
}

output "eu_ipv6" {
  description = "EU node (Hetzner) public IPv6"
  value       = hcloud_server.eu.ipv6_address
}

# Legacy outputs for backwards compatibility
output "vultr_ip" {
  description = "Vultr instance public IPv4 (alias for us_ip)"
  value       = vultr_instance.us.main_ip
}

output "hetzner_ip" {
  description = "Hetzner instance public IPv4 (alias for eu_ip)"
  value       = hcloud_server.eu.ipv4_address
}

# =============================================================================
# SSH Connection Strings
# =============================================================================

output "ssh_us" {
  description = "SSH command for US node (Vultr)"
  value       = "ssh root@${vultr_instance.us.main_ip}"
}

output "ssh_eu" {
  description = "SSH command for EU node (Hetzner)"
  value       = "ssh root@${hcloud_server.eu.ipv4_address}"
}

# =============================================================================
# DNS Configuration (GeoDNS Active/Active)
# =============================================================================

output "dns_ns_records" {
  description = "NS records to configure at your registrar (both authoritative)"
  value = {
    primary_domain = {
      ns1     = "ns1.${var.primary_domain}"
      ns2     = "ns2.${var.secondary_domain}"
      ns1_ip  = vultr_instance.us.main_ip
      ns2_ip  = hcloud_server.eu.ipv4_address
    }
    secondary_domain = {
      ns1     = "ns1.${var.primary_domain}"
      ns2     = "ns2.${var.secondary_domain}"
      ns1_ip  = vultr_instance.us.main_ip
      ns2_ip  = hcloud_server.eu.ipv4_address
    }
  }
}

output "dns_glue_records" {
  description = "Glue records to configure at your registrar"
  value = <<-EOT
    Configure these glue records at your domain registrar:

    For ${var.primary_domain}:
      ns1.${var.primary_domain}   -> ${vultr_instance.us.main_ip}
      ns2.${var.secondary_domain} -> ${hcloud_server.eu.ipv4_address}

    For ${var.secondary_domain}:
      ns1.${var.primary_domain}   -> ${vultr_instance.us.main_ip}
      ns2.${var.secondary_domain} -> ${hcloud_server.eu.ipv4_address}

    GeoDNS will route users to the nearest active node.
  EOT
}

# =============================================================================
# Service URLs (Active/Active - both serve traffic)
# =============================================================================

output "service_urls" {
  description = "Service URLs - GeoDNS routes to nearest region"
  value = {
    billing = "https://billing.${var.primary_domain}"
    proxy   = "https://llm.${var.primary_domain}"

    # Direct regional endpoints (for debugging)
    billing_us = "https://billing-us.${var.primary_domain}"
    billing_eu = "https://billing-eu.${var.secondary_domain}"
    proxy_us   = "https://llm-us.${var.primary_domain}"
    proxy_eu   = "https://llm-eu.${var.secondary_domain}"
  }
}

# =============================================================================
# Ansible Inventory (Active/Active)
# =============================================================================

output "ansible_inventory" {
  description = "Ansible inventory content for active/active deployment"
  value = <<-EOT
    # Auto-generated by Terraform
    # Active/Active Multi-Region Configuration
    # Save to: ansible/inventory/production.yml

    all:
      children:
        us:
          hosts:
            vultr:
              ansible_host: ${vultr_instance.us.main_ip}
              ansible_user: root
              region: us
              node_name: us
              peer_ip: ${hcloud_server.eu.ipv4_address}
              dns_soa: ${var.primary_domain}
              geo_continents: ["NA", "SA", "OC"]

        eu:
          hosts:
            hetzner:
              ansible_host: ${hcloud_server.eu.ipv4_address}
              ansible_user: root
              region: eu
              node_name: eu
              peer_ip: ${vultr_instance.us.main_ip}
              dns_soa: ${var.secondary_domain}
              volume_device: /dev/disk/by-id/scsi-0HC_Volume_${hcloud_volume.postgres_eu.id}
              geo_continents: ["EU", "AF", "AS"]

      vars:
        # Both nodes are active peers
        topology: active_active

        # IP addresses
        us_ip: ${vultr_instance.us.main_ip}
        eu_ip: ${hcloud_server.eu.ipv4_address}

        # Legacy aliases
        vultr_ip: ${vultr_instance.us.main_ip}
        hetzner_ip: ${hcloud_server.eu.ipv4_address}

        # Domains
        primary_domain: ${var.primary_domain}
        secondary_domain: ${var.secondary_domain}

        # PostgreSQL bi-directional replication
        postgres_replication: bidirectional
        postgres_conflict_resolution: last_write_wins
  EOT
}

# =============================================================================
# Cost Estimate (Active/Active)
# =============================================================================

output "estimated_monthly_cost" {
  description = "Estimated monthly infrastructure cost"
  value = <<-EOT
    Active/Active Multi-Region Deployment
    ========================================
    Vultr VC2 (${var.vultr_plan}):     ~$24.00
    Hetzner CX22:                       ~$6.00
    Hetzner Volume (${var.hetzner_volume_size}GB):           ~$1.00
    Domains (2 x annual/12):            ~$3.00
    ----------------------------------------
    Total:                             ~$34.00/month

    Note: Both nodes serve production traffic.
    GeoDNS routes users to nearest region.
  EOT
}

# =============================================================================
# Architecture Summary
# =============================================================================

output "architecture_summary" {
  description = "Active/Active architecture overview"
  value = <<-EOT
    CIRISBridge Active/Active Architecture
    ======================================

    Topology: Active/Active with GeoDNS

    US Node (Vultr Chicago):
      - IP: ${vultr_instance.us.main_ip}
      - Serves: Americas, Oceania
      - PostgreSQL: Read/Write (bi-directional replication)
      - Services: Billing, Proxy, DNS

    EU Node (Hetzner Germany):
      - IP: ${hcloud_server.eu.ipv4_address}
      - Serves: Europe, Africa, Asia
      - PostgreSQL: Read/Write (bi-directional replication)
      - Services: Billing, Proxy, DNS

    Data Consistency: Last-Write-Wins (pglogical)
    Traffic Routing: GeoDNS via Constellation

    Both nodes are equal peers. No primary/secondary distinction.
  EOT
}

# =============================================================================
# Test Environment Outputs (Conditional - 3 server full stack)
# =============================================================================

output "test_infra_ip" {
  description = "Test infra node (PostgreSQL + Lens) public IPv4"
  value       = var.create_test_env ? vultr_instance.test_infra[0].main_ip : null
}

output "test_infra_vpc_ip" {
  description = "Test infra node internal VPC IP"
  value       = var.create_test_env ? vultr_instance.test_infra[0].internal_ip : null
}

output "test_services_ip" {
  description = "Test services node (Billing + Proxy) public IPv4"
  value       = var.create_test_env ? vultr_instance.test_services[0].main_ip : null
}

output "test_services_vpc_ip" {
  description = "Test services node internal VPC IP"
  value       = var.create_test_env ? vultr_instance.test_services[0].internal_ip : null
}

output "test_scout_ip" {
  description = "Test scout node (Manager + Agent) public IPv4"
  value       = var.create_test_env ? vultr_instance.test_scout[0].main_ip : null
}

output "test_scout_vpc_ip" {
  description = "Test scout node internal VPC IP"
  value       = var.create_test_env ? vultr_instance.test_scout[0].internal_ip : null
}

output "ssh_test_infra" {
  description = "SSH command for test infra node"
  value       = var.create_test_env ? "ssh root@${vultr_instance.test_infra[0].main_ip}" : null
}

output "ssh_test_services" {
  description = "SSH command for test services node"
  value       = var.create_test_env ? "ssh root@${vultr_instance.test_services[0].main_ip}" : null
}

output "ssh_test_scout" {
  description = "SSH command for test scout node"
  value       = var.create_test_env ? "ssh root@${vultr_instance.test_scout[0].main_ip}" : null
}

output "test_dns_records" {
  description = "DNS records to add to Cloudflare for test environment"
  value = var.create_test_env ? <<-EOT
    Add these A records to Cloudflare for ${var.primary_domain}:

    lens-test     -> ${vultr_instance.test_infra[0].main_ip}
    billing-test  -> ${vultr_instance.test_services[0].main_ip}
    proxy-test    -> ${vultr_instance.test_services[0].main_ip}
    scout-test    -> ${vultr_instance.test_scout[0].main_ip}
  EOT : null
}

output "test_ansible_inventory" {
  description = "Ansible inventory for test environment"
  value = var.create_test_env ? <<-EOT
    # Test Environment Inventory
    # Save to: ansible/inventory/test.yml
    all:
      children:
        test_infra:
          hosts:
            test-infra:
              ansible_host: ${vultr_instance.test_infra[0].main_ip}
              internal_ip: ${vultr_instance.test_infra[0].internal_ip}

        test_services:
          hosts:
            test-services:
              ansible_host: ${vultr_instance.test_services[0].main_ip}
              internal_ip: ${vultr_instance.test_services[0].internal_ip}
              infra_ip: ${vultr_instance.test_infra[0].internal_ip}

        test_scout:
          hosts:
            test-scout:
              ansible_host: ${vultr_instance.test_scout[0].main_ip}
              internal_ip: ${vultr_instance.test_scout[0].internal_ip}
              services_ip: ${vultr_instance.test_services[0].internal_ip}

      vars:
        ansible_user: root
        primary_domain: ${var.primary_domain}
        environment: test
        postgres_standalone: true
  EOT : null
}

output "test_cost_estimate" {
  description = "Test environment monthly cost"
  value = var.create_test_env ? <<-EOT
    Test Environment (Full Stack)
    =============================
    test-infra (vc2-1c-2gb):    ~$12.00/month  (PostgreSQL + Lens)
    test-services (vc2-2c-4gb): ~$24.00/month  (Billing + Proxy)
    test-scout (vc2-1c-1gb):    ~$6.00/month   (Manager + Agent)
    VPC:                        Free
    ----------------------------------------
    Total when running:         ~$42.00/month
    Total when destroyed:       $0.00/month
  EOT : null
}
